version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
  data_service:
    build: ./data_service
    ports:
      - "5000:5000"
    restart: always
  web_service:
    build: ./web_service
    ports:
      - "5050:5050"
    restart: always
